//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int IDOrder { get; set; }
        public double TotalPrice { get; set; }
        public int Table { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
        public string AddOError { get; set; }
        public System.DateTime Date { get; set; }

        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
