//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int Product_IDProduct { get; set; }
        public int Quantity { get; set; }
        public double TotalPrice { get; set; }
        public int IDOrder { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
